### ISSUE TITLE
Null pointer of role does not have 'indices' defined

### ISSUE THREAD

**Issue by jcantrill** [fabric8io/openshift-elasticsearch-plugin#103]
```
[2017-09-27 20:27:51,130][ERROR][io.fabric8.elasticsearch.plugin.acl.DynamicACLFilter] Exception while syncing ACL with cache
java.lang.NullPointerException
	at io.fabric8.elasticsearch.plugin.acl.SearchGuardRoles.load(SearchGuardRoles.java:185)
	at io.fabric8.elasticsearch.plugin.acl.DynamicACLFilter.syncAcl(DynamicACLFilter.java:170)
	at io.fabric8.elasticsearch.plugin.acl.DynamicACLFilter.process(DynamicACLFilter.java:110)
```
for document like:

```
sg_role_prometheus:
  cluster:
   - METRICS
```

**Comment by jcantrill** [comment]
fixed in #118 for ES5
