### ISSUE TITLE
java.lang.NoClassDefFoundError: org/apache/lucene/index/IndexReader$ReaderClosedListener

### ISSUE THREAD

**Issue by jcantrill** [fabric8io/openshift-elasticsearch-plugin#165]
@lukas-vlcek Thoughts?  I have updates for 6.x here https://github.com/jcantrill/openshift-elasticsearch-plugin/tree/6.x but the integration tests dont even start due to which is missing from the version of the dependency.  I cant seem to figure out the problem.  Maybe its my version of maven?  
```
# Created on 2018-11-28T15:59:54.688
java.lang.NoClassDefFoundError: org/apache/lucene/index/IndexReader$ReaderClosedListener
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
        at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
        at java.lang.Class.getMethod0(Class.java:3018)
        at java.lang.Class.getMethod(Class.java:1784)
        at org.apache.maven.surefire.util.ReflectionUtils.tryGetMethod(ReflectionUtils.java:61)
        at org.apache.maven.surefire.common.junit3.JUnit3TestChecker.isSuiteOnly(JUnit3TestChecker.java:64)
        at org.apache.maven.surefire.common.junit3.JUnit3TestChecker.isValidJUnit3Test(JUnit3TestChecker.java:59)
        at org.apache.maven.surefire.common.junit3.JUnit3TestChecker.accept(JUnit3TestChecker.java:54)
        at org.apache.maven.surefire.common.junit4.JUnit4TestChecker.accept(JUnit4TestChecker.java:52)
        at org.apache.maven.surefire.util.DefaultScanResult.applyFilter(DefaultScanResult.java:98)
        at org.apache.maven.surefire.junit4.JUnit4Provider.scanClassPath(JUnit4Provider.java:309)
        at org.apache.maven.surefire.junit4.JUnit4Provider.setTestsToRun(JUnit4Provider.java:189)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:132)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
Caused by: java.lang.ClassNotFoundException: org.apache.lucene.index.IndexReader$ReaderClosedListener
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 17 more
```

**Comment by jcantrill** [comment]
@lukas-vlcek closer by fixing up the pom but still getting:

```
Exception in thread "Thread-1" java.lang.NoClassDefFoundError: Could not initialize class org.elasticsearch.test.ESTestCase
	at java.lang.Thread.run(Thread.java:748)
	Suppressed: java.lang.IllegalStateException: No context information for thread: Thread[id=13, name=Thread-1, state=RUNNABLE, group=TGRP-AccessControlIntegrationTest]. Is this thread running under a class com.carrotsearch.randomizedtesting.RandomizedRunner runner context? Add @RunWith(class com.carrotsearch.randomizedtesting.RandomizedRunner.class) to your test class. Make sure your code accesses random contexts within @BeforeClass and @AfterClass boundary (for example, static test class initializers are not permitted to access random contexts).
		at com.carrotsearch.randomizedtesting.RandomizedContext.context(RandomizedContext.java:249)
		at com.carrotsearch.randomizedtesting.RandomizedContext.current(RandomizedContext.java:134)
		at com.carrotsearch.randomizedtesting.RandomizedRunner.augmentStackTrace(RandomizedRunner.java:1885)
		at com.carrotsearch.randomizedtesting.RunnerThreadGroup.uncaughtException(RunnerThreadGroup.java:20)
		at java.lang.Thread.dispatchUncaughtException(Thread.java:1959)
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   AccessControlIntegrationTest>ESTestCase.<clinit>:228 » Runtime found jar hell ...
[ERROR]   KibanaIndexModeSharedOpsIntegrationTest.io.fabric8.elasticsearch.KibanaIndexModeSharedOpsIntegrationTest » NoClassDefFound
[ERROR]   KibanaIndexModeUniqueIntegrationTest.io.fabric8.elasticsearch.KibanaIndexModeUniqueIntegrationTest » NoClassDefFound
[ERROR]   ProxyUsernameIntegrationTest.io.fabric8.elasticsearch.ProxyUsernameIntegrationTest » NoClassDefFound
[INFO] 
[ERROR] Tests run: 4, Failures: 0, Errors: 4, Skipped: 0
```
