### ISSUE TITLE
Lazyload EsClient

### ISSUE THREAD

**Issue by jcantrill** [fabric8io/openshift-elasticsearch-plugin#62]
Lazy load the esClient to mute stacks like:

```
ConnectTransportException[[][127.0.0.1:9300] connect_timeout[30s]]; nested: ConnectException[Connection refused: localhost/127.0.0.1:9300];
	at org.elasticsearch.transport.netty.NettyTransport.connectToChannelsLight(NettyTransport.java:967)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:933)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNodeLight(NettyTransport.java:906)
	at org.elasticsearch.transport.TransportService.connectToNodeLight(TransportService.java:267)
	at org.elasticsearch.client.transport.TransportClientNodesService$SimpleNodeSampler.doSample(TransportClientNodesService.java:390)
	at org.elasticsearch.client.transport.TransportClientNodesService$NodeSampler.sample(TransportClientNodesService.java:336)
	at org.elasticsearch.client.transport.TransportClientNodesService.addTransportAddresses(TransportClientNodesService.java:187)
	at org.elasticsearch.client.transport.TransportClient.addTransportAddress(TransportClient.java:243)
	at io.fabric8.elasticsearch.plugin.acl.DynamicACLFilter.<init>(DynamicACLFilter.java:166)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
```

**Comment by jcantrill** [comment]
cc @ewolinetz @richm

**Comment by jcantrill** [comment]
@ewolinetz @richm  Re-evaluating my desire to lazy load this stack.  I see in our initialization we add in the SearchGuard plugins.   Is there any belief that we open up the cluster to NOT use SG for a small window during startup?
